services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: localcontainer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080