import { MoveType } from '@/models/frame-data/move-type';

export const MOVE_SORTING = [
  {
    type: MoveType.Grounded,
    name: 'Grounded',
    sorting: ['jab1', 'jab2', 'jab3', 'rjab', 'dattack', 'usmash', 'fsmash', 'fsmash2', 'dsmash'],
    showInSidebar: true,
  },
  {
    type: MoveType.Tilt,
    name: 'Tilt',
    sorting: ['ftilt', 'uaft', 'daft', 'utilt', 'dtilt'],
    showInSidebar: true,
  },
  {
    type: MoveType.Air,
    name: 'Air',
    sorting: ['nair', 'uair', 'bair', 'fair', 'dair'],
    showInSidebar: true,
  },
  {
    type: MoveType.Special,
    name: 'Special',
    sorting: ['neutralb', 'aneutralb', 'sideb', 'asideb', 'downb', 'adownb', 'upb', 'aupb'],
    showInSidebar: true,
  },
  {
    type: MoveType.Throw,
    name: 'Grab/Throw',
    sorting: [
      'grab',
      'dashgrab',
      'pummel',
      'fthrow',
      'bthrow',
      'uthrow',
      'dthrow',
      'cargo_fthrow',
      'cargo_bthrow',
      'cargo_uthrow',
      'cargo_dthrow',
    ],
    showInSidebar: true,
  },
  {
    type: MoveType.Dodge,
    name: 'Dodge',
    sorting: ['spotdodge', 'airdodge', 'rollbackwards', 'rollforward'],
    showInSidebar: true,
  },
  {
    type: MoveType.Tech,
    name: 'Getups/Techs',
    sorting: ['neutraltech', 'ftechroll', 'btechroll'],
    showInSidebar: true,
  },
  {
    type: MoveType.EdgeAttack,
    name: 'Edge',
    showInSidebar: true,
    sorting: ['edge', 'edgeslow', 'edgeclimb', 'edgeclimbslow', 'edgeroll', 'edgerollslow', 'edgejump', 'edgejumpslow'],
  },
  { type: MoveType.Item, name: 'Item', showInSidebar: false },
  {
    type: MoveType.KirbySpecial,
    name: 'Copy Abilities',
    sorting: [
      'bowserspecial',
      'captainfalconspecial',
      'donkeykongspecial',
      'drmariospecial',
      'falcospecial',
      'foxspecial',
      'ganondorfspecial',
      'iceclimbersspecial',
      'jigglypuffspecial',
      'linkspecial',
      'luigispecial',
      'mariospecial',
      'marthspecial',
      'mewtwospecial',
      'mrgameandwatchspecial',
      'nessspecial',
      'peachspecial',
      'pichuspecial',
      'pikachuspecial',
      'royspecial',
      'samusspecial',
      'sheikspecial',
      'yoshispecial',
      'younglinkspecial',
      'zeldaspecial',
    ],
    showInSidebar: false,
  },
  {
    type: MoveType.Unknown,
    name: 'Uncategorised',
    showInSidebar: false,
  },
];
